% Figure 10: Phase diagram for CFAR thresholding with various distributions.
% Data Dependencies: 
%   DataFig10Uniform.mat  (Generated by GenDataFig10('uniform'))
%   DataFig10Power.mat    (Generated by GenDataFig10('power'))
%   RhoFAR.mat
%

load RhoFAR.mat;

load DataFig10_Uniform.mat;
[Delta, Rho] = meshgrid(deltaArr,rhoArr);
K = ceil(Rho .* floor(N .* Delta));
muErrVecL0 = muErrVecL0 .* K;

str = '(a) Uniform Amplitude Distribution';
subplot(1,2,1);PhasePlot(muErrVecL0, RhoFAR, deltaArr, deltaLen, rhoArr, rhoLen, N, str);

load DataFig10_Power.mat;
[Delta, Rho] = meshgrid(deltaArr,rhoArr);
K = ceil(Rho .* floor(N .* Delta));
muErrVecL0 = muErrVecL0 .* K;

str = '(b) Power-Law Distribution';
subplot(1,2,2);PhasePlot(muErrVecL0, RhoFAR, deltaArr, deltaLen, rhoArr, rhoLen, N, str);

%
% Copyright (c) 2006. David Donoho, Iddo Drori, and Yaakov Tsaig
%  
%
% Part of SparseLab Version:100
% Created Tuesday March 28, 2006
% This is Copyrighted Material
% For Copying permissions see COPYING.m
% Comments? e-mail sparselab@stanford.edu
%
